using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace Comunes.Ayudas.Gestion.F13
{
    /// <summary>
    /// Tipos de sistemas contra incendios, módulo DIPCI
    /// </summary>
    public enum enumAyudasF13 : int
        {
            [Description("SE DESCRIBE LA IDENTIFICACIÓN DEL PELIGRO ENCONTRADO EN UN RECORRIDO DE LA CSH, UNA INSPECCIÓN PLANEADA, CAUSAS BÁSICAS E INMEDIATAS DE INCIDENTES O ACCIDENTES, REPORTES DEL PERSONAL DE CONDICIONES INSEGURAS O LO DECLARADO EN LAS COLUMNAS DE CONTROLES RECOMENDADOS Y CURSOS DE CAPACITACIÓN DEL REGISTRO DE IDENTIFICACIÓN DE PELIGROS P - 1020 - 007 - R - 02 O DE LOS CONTROLES RECOMENDADOS DEL REGISTRO HOJA DE ANÁLISIS DE TAREAS CRÍTICAS P - 1020 - 007 - R - 03")]
            txtOrigen = 1,
            [Description("CUANDO APLIQUE LA ELABORACIÓN DE UNA SOLICITUD DE TRABAJO SE DEBE PONER EL NÚMERO O EN SU CASO EL NÚMERO DEL AVISO DE AVERIA DEL R / 3 O SOLICITUD DE PEDIDO / SERVICIO, FACTURA O EN SU CASO DE NO APLICAR SE DEJA EN BLANCO ESTA COLUMNA")]
            txtOrden = 2,
            [Description("Nivel I. Responsable de especialidad, departamento o agencia. Nivel II. Suptte. Zona, Jefe cetro de trabajo.Nivel III.Gerentes / Subgerentes")]
            txtNivel = 3,
            [Description(" SE DESCRIBE LA IDENTIFICACIÓN DEL PELIGRO ENCONTRADO EN UN RECORRIDO DE LA CSH, UNA INSPECCIÓN PLANEADA, CAUSAS BÁSICAS E INMEDIATAS DE INCIDENTES O ACCIDENTES, REPORTES DEL PERSONAL DE CONDICIONES INSEGURAS O LO DECLARADO EN LAS COLUMNAS DE  CONTROLES RECOMENDADOS Y CURSOS DE CAPACITACIÓN DEL REGISTRO DE IDENTIFICACIÓN DE PELIGROS P - 1020 - 007 - R - 02 O DE LOS CONTROLES RECOMENDADOS DEL REGISTRO HOJA DE ANÁLISIS DE TAREAS CRÍTICAS P - 1020 - 007 - R - 03")]
            txtidentificacion = 4,
            [Description("SE ANOTA EL NOMBRE DEL RESPONSABLE DE REALIZAR LA CORRECIÓN DICTADA EN LA MEDIDA PREVENTIVO - CORRECTIVA")]
            txtRespEjecucion = 5
           
        }
    
}